# Generated by Django 3.0.2 on 2020-01-18 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_text', models.CharField(max_length=100)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='quiz.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer_text', models.CharField(max_length=255)),
                ('Question_related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='quiz.Question')),
            ],
        ),
    ]
