# Generated by Django 3.0.2 on 2020-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Weightage',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
