# Generated by Django 3.0.2 on 2020-01-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='from_Domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_domain', to='quiz.Domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='Question_related_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='quiz.Question'),
        ),
    ]
