# Generated by Django 3.0.2 on 2020-01-19 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20200118_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology', models.PositiveIntegerField(null=True)),
                ('Marketing', models.PositiveIntegerField(null=True)),
                ('Total', models.PositiveIntegerField(null=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_domain', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_text', models.CharField(max_length=100)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_specific', to='quiz.Domain')),
            ],
        ),
    ]
