# Generated by Django 3.0.2 on 2020-01-19 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_domainquestion_generalsolution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralSolution',
            new_name='GeneralMarks',
        ),
        migrations.CreateModel(
            name='DomainMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.PositiveIntegerField(null=True)),
                ('Domain_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_finalspecs', to='quiz.Domain')),
                ('Name_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='for_final_marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
