# Generated by Django 3.0.2 on 2020-01-19 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0006_domainanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='from_Domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_domain', to='quiz.Domain'),
        ),
        migrations.AlterField(
            model_name='domainmarks',
            name='Name_of_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_final_marks', to=settings.AUTH_USER_MODEL),
        ),
    ]
