# Generated by Django 3.0.2 on 2020-01-19 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0007_auto_20200119_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmarks',
            name='Domain_final',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='generalmarks',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_domain', to=settings.AUTH_USER_MODEL),
        ),
    ]
